# Payment Service Centralized Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: Murali@3824
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

payment:
  razorpay:
    key-id: rzp_test_RtYX5QM7jHMepM
    key-secret: gBDqpAEGxmbGXsscKeNmp6v5
  stripe:
    secret-key: sk_test_51Sg5B3BF3wsJmLZM4kCHjnVluZ8wyZ5boyHILUCmYxAgGWMmdIiQSdt8lzkSDrb3NniYfD2Fg62rhB3jvUQN5AHo00vvhbxx8k
